<template>
  <!-- eslint-disable-next-line vue/no-v-html -- svg is generated by the trusted @nimiq/identicons library, no user input -->
  <div :style="{ width: `${size}px`, height: `${size}px` }" v-html="svgContent" />
</template>

<script setup lang="ts">
import Identicons from '@nimiq/identicons/dist/identicons.bundle.min.js';
import { ref, watchEffect } from 'vue';

const props = withDefaults(defineProps<{ size?: number; address?: string | null }>(), {
  size: 38,
  address: null,
});

const svgContent = ref(Identicons.placeholder('#bbb', 1));

watchEffect(async () => {
  if (props.address) {
    svgContent.value = await Identicons.svg(props.address);
  } else {
    svgContent.value = Identicons.placeholder('#bbb', 1);
  }
});
</script>

<style scoped>
div :deep(svg) {
  width: 100%;
  height: 100%;
  display: block;
}
</style>
